name: â²ï¸ Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: â²ï¸ WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          BLOCKS: "â¬œğŸŸ¨ğŸŸ©"
          COMMIT_MESSAGE: "docs: update waka-readme graph with new metrics"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
